# Generated by Django 3.0.3 on 2020-02-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldierdata',
            name='Rank',
            field=models.CharField(blank=True, choices=[('PVT', 'PVT'), ('PV2', 'PV2'), ('PFC', 'PFC'), ('SPC', 'SPC'), ('SGT', 'SGT'), ('SSG', 'SSG'), ('SFC', 'SFC'), ('MSG', 'MSG'), ('2LT', '2LT'), ('1LT', '1LT'), ('CPT', 'CPT'), ('MAJ', 'MAJ'), ('WO1', 'WO1'), ('CW2', 'CW2'), ('CW3', 'CW3')], default='PVT', max_length=155),
        ),
    ]
