# Generated by Django 3.0.3 on 2020-02-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldierdata',
            name='Position',
            field=models.CharField(choices=[('TD', 'Tactical Director'), ('TDA', 'Tactical Director Assistant'), ('TCO', 'Tactical Control Officer'), ('TCA', 'Tactical Control Assistant'), ('TPW', 'Early Warning Operator'), ('RO', 'Radio Operator/ Reports operator'), ('JWARN', 'JWARN Operator')], default='', max_length=155),
        ),
    ]
