# Generated by Django 3.0.3 on 2020-02-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0003_auto_20200227_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldierdata',
            name='Platoon',
            field=models.CharField(blank=True, choices=[('Fire Control', 'Fire Control'), ('Launcher', 'Launcher'), ('Fire Direction Control', 'Fire Direction Control')], max_length=155),
        ),
        migrations.AlterField(
            model_name='soldierdata',
            name='Position',
            field=models.CharField(blank=True, choices=[('TD', 'Tactical Director'), ('TDA', 'Tactical Director Assistant'), ('TCO', 'Tactical Control Officer'), ('TCA', 'Tactical Control Assistant'), ('TPW', 'Early Warning Operator'), ('RO', 'Radio Operator/ Reports operator'), ('JWARN', 'JWARN Operator')], max_length=155),
        ),
    ]
