# Generated by Django 3.0.3 on 2020-02-28 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0004_auto_20200228_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldierdata',
            name='AAMDC',
        ),
        migrations.RemoveField(
            model_name='soldierdata',
            name='Brigade',
        ),
    ]
