# Generated by Django 3.0.3 on 2020-02-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0005_auto_20200228_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldierdata',
            name='Battalion',
            field=models.CharField(blank=True, choices=[('4-3 ADA', '4-3 ADA'), ('3-2 ADA', '3-2 ADA')], max_length=155),
        ),
        migrations.AlterField(
            model_name='soldierdata',
            name='Battery',
            field=models.CharField(blank=True, choices=[('HHB', 'HHB'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=155),
        ),
    ]
